### ISSUE TITLE
Link to CLA 1.1 is broken

### ISSUE THREAD

**Issue by t-sommer** [modelica/ModelicaAssociationCLA#3]
see https://app.circleci.com/pipelines/github/modelica/fmi-standard/2065/workflows/8fb4e043-b544-4e62-9a2e-026c42ffe5e4/jobs/3843

**Comment by beutlich** [comment]
You can link to CLA v1.1.1 at https://modelica.org/licenses/ModelicaAssociationCLA_1.1.1.html instead.

**Comment by beutlich** [comment]
> You can link to CLA v1.1.1 at https://modelica.org/licenses/ModelicaAssociationCLA_1.1.1.html instead.

That link is still gone, even after closed https://github.com/modelica/www.modelica.org/issues/45.

**Comment by t-sommer** [comment]
https://modelica.org/licenses/ModelicaAssociationCLA_1.1.1.html is simply forwarding to https://github.com/modelica/ModelicaAssociationCLA/releases. Do we still need it?

**Comment by beutlich** [comment]
Hm, since the issue was originally raised by fmi-standard pipeline, I believe it can be closed now.
